#!/bin/bash
#PBS -l walltime=12:00:00
#PBS -M kevin5@ualberta.ca
#PBS -l mem=20gb
#PBS -m bea
#PBS -l procs=16
cd $PBS_O_WORKDIR

module load application/stacks/1.24

perl ~/GBS_analysis-2015-01-13/populations_stacks.pl -p 2 -r 0.25 -m 2 -a 0 -P ~/GBS_analysis-2015-01-13/Papilio_notrim_ustacks/STACKS_OUTFILES -M ~/GBS_analysis-2015-01-13/papilio_population_map.txt -t 16 -f fasta -o ~/GBS_analysis-2015-01-13/Papilio_notrim_populations
perl ~/GBS_analysis-2015-01-13/populations_stacks.pl -p 2 -r 0.25 -m 2 -a 0 -P ~/GBS_analysis-2015-01-13/Papilio_trim_offset_3_padded_ustacks/STACKS_OUTFILES -M ~/GBS_analysis-2015-01-13/papilio_population_map.txt -t 16 -f fasta -o ~/GBS_analysis-2015-01-13/Papilio_trim_offset_3_padded_populations
perl ~/GBS_analysis-2015-01-13/populations_stacks.pl -p 2 -r 0.25 -m 2 -a 0 -P ~/GBS_analysis-2015-01-13/Papilio_trim_offset_5_padded_ustacks/STACKS_OUTFILES -M ~/GBS_analysis-2015-01-13/papilio_population_map.txt -t 16 -f fasta -o ~/GBS_analysis-2015-01-13/Papilio_trim_offset_5_padded_populations

