#!/bin/sh
perl ~/GBS_analysis-2015-01-13/refgen_stacks_analysis_pipeline.pl -i ~/GBS_analysis-2015-01-13/Stephen_MPB/PstI_MspI_GBS_NO_TRIM -p MPB-MALE-GBS -g ~/GBS_analysis-2015-01-13/Stephen_MPB/DendPond_male_1.0/Primary_Assembly/unplaced_scaffolds/FASTA/DendPond_male_1.0_unplaced.scaf.fa -t gzfastq -c 10 -o ~/GBS_analysis-2015-01-13/Stephen_MPB/MPB_MALE_GBS_no_trim_refgen_stacks
perl ~/GBS_analysis-2015-01-13/refgen_stacks_analysis_pipeline.pl -i ~/GBS_analysis-2015-01-13/Stephen_MPB/PstI_MspI_GBS_TRIMMED_ADAPTER_UNPADDED_DIR/TRIMMED_OFFSET_3_ADAPTOR_REGEX_PARALLEL_FASTQ_DIR -p MPB-MALE-GBS -g ~/GBS_analysis-2015-01-13/Stephen_MPB/DendPond_male_1.0/Primary_Assembly/unplaced_scaffolds/FASTA/DendPond_male_1.0_unplaced.scaf.fa -t gzfastq -c 10 -o ~/GBS_analysis-2015-01-13/Stephen_MPB/MPB_MALE_GBS_trim_offset_3_refgen_stacks
perl ~/GBS_analysis-2015-01-13/refgen_stacks_analysis_pipeline.pl -i ~/GBS_analysis-2015-01-13/Stephen_MPB/PstI_MspI_GBS_TRIMMED_ADAPTER_UNPADDED_DIR/TRIMMED_OFFSET_5_ADAPTOR_REGEX_PARALLEL_FASTQ_DIR -p MPB-MALE-GBS -g ~/GBS_analysis-2015-01-13/Stephen_MPB/DendPond_male_1.0/Primary_Assembly/unplaced_scaffolds/FASTA/DendPond_male_1.0_unplaced.scaf.fa -t gzfastq -c 10 -o ~/GBS_analysis-2015-01-13/Stephen_MPB/MPB_MALE_GBS_trim_offset_5_refgen_stacks
perl ~/GBS_analysis-2015-01-13/refgen_stacks_analysis_pipeline.pl -i ~/GBS_analysis-2015-01-13/Stephen_MPB/PstI_MspI_GBS_NO_TRIM -p MPB-FEMALE-GBS -g ~/GBS_analysis-2015-01-13/Stephen_MPB/DendPond_female_1.0/Primary_Assembly/unplaced_scaffolds/FASTA/DendPond_female_1.0_unplaced.scaf.fa -t gzfastq -c 10 -o ~/GBS_analysis-2015-01-13/Stephen_MPB/MPB_FEMALE_GBS_no_trim_refgen_stacks
perl ~/GBS_analysis-2015-01-13/refgen_stacks_analysis_pipeline.pl -i ~/GBS_analysis-2015-01-13/Stephen_MPB/PstI_MspI_GBS_TRIMMED_ADAPTER_UNPADDED_DIR/TRIMMED_OFFSET_3_ADAPTOR_REGEX_PARALLEL_FASTQ_DIR -p MPB-FEMALE-GBS -g ~/GBS_analysis-2015-01-13/Stephen_MPB/DendPond_female_1.0/Primary_Assembly/unplaced_scaffolds/FASTA/DendPond_female_1.0_unplaced.scaf.fa -t gzfastq -c 10 -o ~/GBS_analysis-2015-01-13/Stephen_MPB/MPB_FEMALE_GBS_trim_offset_3_refgen_stacks
perl ~/GBS_analysis-2015-01-13/refgen_stacks_analysis_pipeline.pl -i ~/GBS_analysis-2015-01-13/Stephen_MPB/PstI_MspI_GBS_TRIMMED_ADAPTER_UNPADDED_DIR/TRIMMED_OFFSET_5_ADAPTOR_REGEX_PARALLEL_FASTQ_DIR -p MPB-FEMALE-GBS -g ~/GBS_analysis-2015-01-13/Stephen_MPB/DendPond_female_1.0/Primary_Assembly/unplaced_scaffolds/FASTA/DendPond_female_1.0_unplaced.scaf.fa -t gzfastq -c 10 -o ~/GBS_analysis-2015-01-13/Stephen_MPB/MPB_FEMALE_GBS_trim_offset_5_refgen_stacks
perl ~/GBS_analysis-2015-01-13/unique_stacks_analysis_pipeline.pl -i ~/GBS_analysis-2015-01-13/Stephen_MPB/PstI_MspI_GBS_NO_TRIM -t gzfastq -c 10 -o ~/GBS_analysis-2015-01-13/Stephen_MPB/MPB_GBS_notrim_unique_stacks
perl ~/GBS_analysis-2015-01-13/unique_stacks_analysis_pipeline.pl -i ~/GBS_analysis-2015-01-13/Stephen_MPB/PstI_MspI_GBS_TRIMMED_ADAPTER_PADDED_DIR/TRIMMED_OFFSET_3_ADAPTOR_REGEX_PARALLEL_FASTQ_DIR -t gzfastq -c 10 -o ~/GBS_analysis-2015-01-13/Stephen_MPB/MPB_GBS_trim_offset_3_unique_stacks
perl ~/GBS_analysis-2015-01-13/unique_stacks_analysis_pipeline.pl -i ~/GBS_analysis-2015-01-13/Stephen_MPB/PstI_MspI_GBS_TRIMMED_ADAPTER_PADDED_DIR/TRIMMED_OFFSET_5_ADAPTOR_REGEX_PARALLEL_FASTQ_DIR -t gzfastq -c 10 -o ~/GBS_analysis-2015-01-13/Stephen_MPB/MPB_GBS_trim_offset_5_unique_stacks


